### PR TITLE
Update how we build dependencies for Windows. Retarget for Windows 7.

### LINKED ISSUE #3: Consider updating the version of Windows targeted from XP to Windows 7
Currently we target Windows XP which is deprecated and unsupported by Microsoft. Most people are using at least Windows 7(which is also near its end of support by Microsoft, but is still used by some people who object to Microsoft's current directions.). It makes sense to stop supporting Windows XP.  Updating this would resolve an issue with modernizing the code base where TCHAR on XP is a local multibyte encoding, but on Windows 7 it should be UTF-16.

### PR DESCRIPTION
**Pull request by ghost**
This pull request is meant to resolve #3 and make the build process easier to update in the future.  Currently we have statically downloaded and unzipped folders for fixed versions, that requires manual updating.  This pull request adds some cmake files that use external projects to download and build the dependencies.

Updating dependencies in the future should be as easy as changing the upstream url in the cmake file. Currently this uses some hardcoded assumptions that we are building for Windows. After this is working and approved, it is hoped that we can extend this same process for building dependencies on other platforms supported by cmake.

In its current state there are still some issues being fixed, but I am starting this pull request now to get some feedback from the appveyor builds.

### CODE REVIEW

**Comment by ghost** [comment]
This should be in a state where it is ready to be tested, I don't have access to a device with Windows 7, but I can try using a VM later.

**Comment by timfel** [comment]
Wow, I did not know `ExternalProject_Add` is so flexible, even downloading sources etc. Cool stuff!

**Comment by ghost** [comment]
Yeah after doing the first version of the lua dependencies in stratagus, it is starting to be a hammer-nail situation(when all you have is a hammer, everything looks like a nail) for me with cmake and ExternalProject_Add.

**Comment by timfel** [comment]
SDL2 is not part of this PR. Is that on purpose?

**Comment by timfel** [comment]
Also, I would suggest we add commit shas (`GIT_TAG`) for all subrepository builds

**Comment by timfel** [comment]
I also needed to update this in stratagus FindTolua++:
```diff
-	find_library(TOLUA++_LIBRARY NAMES tolua++ tolua++5.1 toluapp)
-	find_program(TOLUA++_APP NAMES tolua++ tolua++5.1 toluapp)
+	find_library(TOLUA++_LIBRARY NAMES tolua++ tolua++5.1 toluapp toluapp51)
+	find_program(TOLUA++_APP NAMES tolua++ tolua++5.1 toluapp toluapp51)
```

I also added this in `.vscode/settings.json` to quickly build locally
```
{
    "cmake.generator": "Visual Studio 16 2019",
    "cmake.platform": "win32",
    "cmake.toolset": "v142",
    "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools"
}
```

And I tried with these for SDL
```
  ExternalProject_Add(
    sdl2
    PREFIX sdl2
    GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
    GIT_TAG b7a0200aab8088e04800d33cc88fee384df0d78c
    CMAKE_ARGS -DCMAKE_SYSTEM_VERSION=8.1
               -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/contrib
         )
  
  ExternalProject_Add(
    sdl2_mixer
    PREFIX sdl2_mixer
    GIT_REPOSITORY https://github.com/libsdl-org/SDL_mixer.git
    GIT_TAG cfc9f77077a323df0f348651bf46712f35e4c4f4
    CMAKE_ARGS -DCMAKE_SYSTEM_VERSION=8.1
                -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/contrib
                -DCMAKE_PREFIX_PATH=${CMAKE_BINARY_DIR}/contrib
    DEPENDS sdl2 zlib theora vorbis ogg)
  
  ExternalProject_Add(
    sdl2_image
    PREFIX sdl2_image
    GIT_REPOSITORY https://github.com/libsdl-org/SDL_image.git
    GIT_TAG 63efffb9f2d66f760a4c4b06d9d28077ebebebb8
    CMAKE_ARGS -DCMAKE_SYSTEM_VERSION=8.1
                -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/contrib
                -DCMAKE_PREFIX_PATH=${CMAKE_BINARY_DIR}/contrib
    DEPENDS sdl2 zlib png jpeg mng)
 ```
```

**Comment by ghost** [comment]
For the SDL2, I meant to ask you if we wanted to build or just still unpack.  Sorry, things got a bit hectic at work due to the upcoming holidays.  I totally agree on the `GIT_TAG`s I can add those in.  I will add in your SDL bits as well.

For testing against future changes in upstream dependencies, we could also add some Github actions job to build these without the `GIT_TAG`s and see if/when we get a build failure as a warning of future changes.  I have seen also someone recently suggest using Apache Guacamole to test GUI applications in a CI build.  I think Fedora and OpenSuse also have some methods for automated testing of GUI programs. It might make sense to add those in at some point in the future.

**Comment by ghost** [comment]
If this is last build is working, then to make it cross platform, we should only need to change the few lines that are windows specific and put them behind some checks and add some PROJECTS_ARGS variable to pass the `-DCMAKE_SYSTEM_VERSION=8.1` on to the ExternalProjects(they don't seem to inherit all the flags of the parent project).  I haven't tried it on Linux yet, but the only project I am expecting to have issues building there is the libtheora one, since I don't think it has had much/any testing on linux.  I should be able to test this a bit later today on Windows 10.

**Comment by ghost** [comment]
Looks like a build error using SDL2_mixer, I can fix that later today.  I just added your SDL external projects for that, but they may need some tweaking. 

Edit: I think this was introduced as an error by adding git_shallow.

**Comment by abenedic** [comment]
For some reason locally I couldn't download the SDL2 git repo for the version you used. But I could do just the tagged release.  I then stupidly tried that for SDL2_image, but it only has a CMake build file on master, so I changed that tag as well.

**Comment by ghost** [comment]
Still getting the same error as the AppVeyor 
```
"C:\Users\Alex\Documents\GitHub\build\win32_stratagus_dependencies.sln" (default target) (1) ->
"C:\Users\Alex\Documents\GitHub\build\sdl2_mixer.vcxproj.metaproj" (default target) (21) ->
"C:\Users\Alex\Documents\GitHub\build\sdl2_mixer.vcxproj" (default target) (26) ->
(CustomBuild target) ->
  MSBUILD : error MSB1009: Project file does not exist. [C:\Users\Alex\Documents\GitHub\build\sdl2_mixer.vcxproj]
  C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(242,5): error MSB8066: Custom build for 'C:\Users\Alex\Documents\GitHub\build\CMakeFiles\d8bddaad9d9642aec83de253674fb64a\sd
l2_mixer-mkdir.rule;C:\Users\Alex\Documents\GitHub\build\CMakeFiles\d8bddaad9d9642aec83de253674fb64a\sdl2_mixer-download.rule;C:\Users\Alex\Documents\GitHub\build\CMakeFiles\d8bddaad9d9642aec83de253674fb64a\sdl2_mixer-update.rule;C:\Use
rs\Alex\Documents\GitHub\build\CMakeFiles\d8bddaad9d9642aec83de253674fb64a\sdl2_mixer-patch.rule;C:\Users\Alex\Documents\GitHub\build\CMakeFiles\d8bddaad9d9642aec83de253674fb64a\sdl2_mixer-configure.rule;C:\Users\Alex\Documents\GitHub\b
uild\CMakeFiles\d8bddaad9d9642aec83de253674fb64a\sdl2_mixer-build.rule;C:\Users\Alex\Documents\GitHub\build\CMakeFiles\d8bddaad9d9642aec83de253674fb64a\sdl2_mixer-install.rule;C:\Users\Alex\Documents\GitHub\build\CMakeFiles\9fff277907ae
0f19d7f29ec3045a1311\sdl2_mixer-complete.rule;C:\Users\Alex\Documents\GitHub\build\CMakeFiles\261e2e552d078ae6ada0d999b3f95273\sdl2_mixer.rule;C:\Users\Alex\Documents\GitHub\win32-stratagus-dependencies\CMakeLists.txt' exited with code
1. [C:\Users\Alex\Documents\GitHub\build\sdl2_mixer.vcxproj]

    601 Warning(s)
    2 Error(s)

```
Not quite sure what is wrong, I will try looking more into it tomorrow.

**Pull request closed without merging**
